// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJYG6A_zd42fwL7WYimEtbaXfOJDzbcA',
    appId: '1:475287115559:web:c767618517f31216a37b02',
    messagingSenderId: '475287115559',
    projectId: 'alzcare-ffc04',
    authDomain: 'alzcare-ffc04.firebaseapp.com',
    storageBucket: 'alzcare-ffc04.firebasestorage.app',
    measurementId: 'G-8LK00HBM20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsg16Cs7rONeB-pfbeEjaHBPfBOgRu2UY',
    appId: '1:475287115559:android:8e4aabdb3bf9671da37b02',
    messagingSenderId: '475287115559',
    projectId: 'alzcare-ffc04',
    storageBucket: 'alzcare-ffc04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyOD0tTzqPGEgD2jylbRx6NJCfpIzfdN4',
    appId: '1:475287115559:ios:3d6568621f19413aa37b02',
    messagingSenderId: '475287115559',
    projectId: 'alzcare-ffc04',
    storageBucket: 'alzcare-ffc04.firebasestorage.app',
    iosBundleId: 'com.example.alzcare.alzcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyOD0tTzqPGEgD2jylbRx6NJCfpIzfdN4',
    appId: '1:475287115559:ios:3d6568621f19413aa37b02',
    messagingSenderId: '475287115559',
    projectId: 'alzcare-ffc04',
    storageBucket: 'alzcare-ffc04.firebasestorage.app',
    iosBundleId: 'com.example.alzcare.alzcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtJYG6A_zd42fwL7WYimEtbaXfOJDzbcA',
    appId: '1:475287115559:web:81e32d0a8b0ce0c7a37b02',
    messagingSenderId: '475287115559',
    projectId: 'alzcare-ffc04',
    authDomain: 'alzcare-ffc04.firebaseapp.com',
    storageBucket: 'alzcare-ffc04.firebasestorage.app',
    measurementId: 'G-NHRE8H69X3',
  );
}
